
PERSON = 'person'
VEHICLE = 'vehicle'

classes_converter = {
    "person": PERSON,
    "bicycle": VEHICLE,
    "car": VEHICLE,
    "motorbike": VEHICLE,
    "aeroplane": VEHICLE,
    "bus": VEHICLE,
    "train": VEHICLE,
    "truck": VEHICLE,
    "boat": VEHICLE,
    "traffic light": None,
    "fire hydrant": None,
    "stop sign": None,
    "parking meter": None,
    "bench": None,
    "bird": None,
    "cat": None,
    "dog": None,
    "horse": None,
    "sheep": None,
    "cow": None,
    "elephant": None,
    "bear": None,
    "zebra": None,
    "giraffe": None,
    "backpack": None,
    "umbrella": None,
    "handbag": None,
    "tie": None,
    "suitcase": None,
    "frisbee": None,
    "skis": None,
    "snowboard": None,
    "sports ball": None,
    "kite": None,
    "baseball bat": None,
    "baseball glove": None,
    "skateboard": None,
    "surfboard": None,
    "tennis racket": None,
    "bottle": None,
    "wine glass": None,
    "cup": None,
    "fork": None,
    "knife": None,
    "spoon": None,
    "bowl": None,
    "banana": None,
    "apple": None,
    "sandwich": None,
    "orange": None,
    "broccoli": None,
    "carrot": None,
    "hot dog": None,
    "pizza": None,
    "donut": None,
    "cake": None,
    "chair": None,
    "sofa": None,
    "potted plant": None,
    "bed": None,
    "dining table": None,
    "toilet": None,
    "tvmonitor": None,
    "laptop": None,
    "mouse": None,
    "remote": None,
    "keyboard": None,
    "cell phone": None,
    "microwave": None,
    "oven": None,
    "toaster": None,
    "sink": None,
    "refrigerator": None,
    "book": None,
    "clock": None,
    "vase": None,
    "scissors": None,
    "teddy bear": None,
    "hair drier": None,
    "toothbrush": None,
}
